{
  "deprecated": false,
  "cpeName": "cpe:2.3:a:ibm:db2_connect:11.1.0.0:*:*:*:enterprise:*:*:*",
  "cpeNameId": "D8070A41-A5CA-4340-8CB7-77BA9B9EC1BD",
  "created": "2017-05-04T18:42:22.397",
  "lastModified": "2017-05-04T18:42:22.397",
  "titles": [
    {
      "title": "IBM DB2 Connect 11.1.0.0 Enterprise",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "http://www-01.ibm.com/support/docview.wss?uid=swg21990061",
      "type": "Advisory"
    },
    {
      "ref": "https://www-945.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/DB2&release=All&platform=All&function=fixId&fixids=special_35742_DB2-linuxppc64le-universal_fixpack-11.1.0.0-FP000%3A771884133768041088&includeSupersedes=0",
      "type": "Version"
    },
    {
      "ref": "http://www.ibm.com/us-en/?lnk=m",
      "type": "Vendor"
    }
  ]
}
