{
  "deprecated": false,
  "cpeName": "cpe:2.3:a:python:python:3.10.9:*:*:*:*:*:*:*",
  "cpeNameId": "1ABB19A6-C69B-4290-B8E1-518199B48AE6",
  "created": "2022-11-09T18:08:34.697",
  "lastModified": "2022-11-14T15:04:27.800",
  "titles": [
    {
      "title": "Python 3.10.9",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "https://github.com/CVEProject/cvelist/blob/master/2022/45xxx/CVE-2022-45061.json",
      "type": "Advisory"
    },
    {
      "ref": "https://github.com/python/cpython/tags",
      "type": "Version"
    },
    {
      "ref": "https://github.com/python/cpython/issues/98433",
      "type": "Advisory"
    }
  ]
}
