{
	"deprecated": true,
	"cpeName": "cpe:2.3:a:python:python:3.6:*:*:*:*:*:*:*",
	"cpeNameId": "2696B99E-AC0B-4221-87BD-F2CA47F7B069",
	"created": "2017-11-30T15:38:25.837",
	"lastModified": "2021-01-06T16:11:15.250",
	"titles": [
		{
			"title": "Python 3.6",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://bugs.python.org/issue27850",
			"type": "Advisory"
		},
		{
			"ref": "https://www.python.org/",
			"type": "Vendor"
		}
	],
	"deprecatedBy": [
		{
			"cpeName": "cpe:2.3:a:python:python:3.6.0:-:*:*:*:*:*:*",
			"cpeNameId": "759B3F1F-81C9-4EAF-87D2-F03F356B46DE"
		}
	]
}
