{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:python:python:3.10.8:*:*:*:*:*:*:*",
	"cpeNameId": "F52C9372-9A85-4315-80DF-7F3F892D605F",
	"created": "2022-11-07T17:25:43.143",
	"lastModified": "2022-11-09T16:47:58.307",
	"titles": [
		{
			"title": "Python 3.10.8",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://github.com/python/cpython/issues/97514",
			"type": "Advisory"
		}
	]
}
