{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:x.org:x_server:1.20.10:*:*:*:*:*:*:*",
	"cpeNameId": "C9B41B2D-B04F-44EF-91C7-1F0BC174E606",
	"created": "2020-12-16T18:58:23.677",
	"lastModified": "2020-12-16T18:58:23.677",
	"titles": [
		{
			"title": "X.Org X Server 1.20.10",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://bugzilla.redhat.com/show_bug.cgi?id=1887276",
			"type": "Advisory"
		},
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/192533",
			"type": "Advisory"
		},
		{
			"ref": "https://www.x.org/releases/individual/xserver/",
			"type": "Change Log"
		}
	]
}
