{
  "deprecated": false,
  "cpeName": "cpe:2.3:a:ibm:datapower_gateway:2018.4.1.8:*:*:*:*:*:*:*",
  "cpeNameId": "CC65E7E3-E70B-4570-A41B-A538C397A5B9",
  "created": "2020-03-19T17:23:39.807",
  "lastModified": "2020-03-19T17:23:39.807",
  "titles": [
    {
      "title": "IBM DataPower Gateway 2018.4.1.8",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "https://www.ibm.com/support/pages/fix-packs-datapower-gateway-version-20184",
      "type": "Version"
    }
  ]
}
