{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:12.0.2:*:*:*:*:*:*:*",
	"cpeNameId": "0AEEAE30-35DC-481B-AB65-160148BD8F03",
	"created": "2024-08-01T14:45:56.157",
	"lastModified": "2024-08-01T14:45:56.157",
	"titles": [
		{
			"title": "IBM Cognos Analytics 12.0.2",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/283364",
			"type": "Advisory"
		}
	]
}
