{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack4:*:*:*:*:*:*",
	"cpeNameId": "210DF6C3-76DD-4FE4-815F-968BB9516F5C",
	"created": "2021-12-06T16:24:11.760",
	"lastModified": "2021-12-09T21:07:53.453",
	"titles": [
		{
			"title": "IBM Cognos Analytics 11.1.7 Fix Pack 4",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://www.ibm.com/docs/en/cognos-analytics/11.1.0?topic=1117-release-fp4-november-2021",
			"type": "Change Log"
		}
	]
}
