{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:12.0.1:*:*:*:*:*:*:*",
	"cpeNameId": "2476636A-BC6E-44C8-A1AC-C57FA8A9768D",
	"created": "2024-08-01T14:45:56.157",
	"lastModified": "2024-08-01T14:45:56.157",
	"titles": [
		{
			"title": "IBM Cognos Analytics 12.0.1",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/283364",
			"type": "Advisory"
		}
	]
}
