{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.2.2:*:*:*:*:*:*:*",
	"cpeNameId": "71FAD1FD-BF2C-4CCF-AEDE-3EE818D7ACEC",
	"created": "2024-08-01T14:45:56.157",
	"lastModified": "2024-08-01T14:45:56.157",
	"titles": [
		{
			"title": "IBM Cognos Analytics 11.2.2",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/283364",
			"type": "Advisory"
		}
	]
}
