{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:12.0.0:*:*:*:*:*:*:*",
	"cpeNameId": "B295F212-FADA-4C36-B83F-AB6CA7681B3E",
	"created": "2024-08-01T14:45:56.157",
	"lastModified": "2024-08-01T14:45:56.157",
	"titles": [
		{
			"title": "IBM Cognos Analytics 12.0.0",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/283364",
			"type": "Advisory"
		}
	]
}
