{
  "deprecated": false,
  "cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.0.13:fixpack2:*:*:*:*:*:*",
  "cpeNameId": "C8C96020-1EDA-47BD-8941-AF8E74405B72",
  "created": "2020-03-17T12:28:57.863",
  "lastModified": "2020-03-17T12:28:57.863",
  "titles": [
    {
      "title": "IBM Cognos Analytics 11.0.13 Fix Pack 2",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=Cognos&product=ibm/Information+Management/Cognos+Analytics&release=11.0.13&platform=All&function=all",
      "type": "Version"
    }
  ]
}
