{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.2.3:*:*:*:*:*:*:*",
	"cpeNameId": "C906C616-D4C7-405B-8A74-98AFD362B138",
	"created": "2022-09-06T16:21:20.663",
	"lastModified": "2022-11-18T17:27:05.287",
	"titles": [
		{
			"title": "IBM Cognos Analytics 11.2.3",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/233571",
			"type": "Advisory"
		}
	]
}
