{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.1.7:fixpack3:*:*:*:*:*:*",
	"cpeNameId": "E492DC7C-1CC0-4681-9555-3D530A30FB73",
	"created": "2021-12-06T16:23:48.037",
	"lastModified": "2021-12-09T21:07:53.453",
	"titles": [
		{
			"title": "IBM Cognos Analytics 11.1.7 Fix Pack 3",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://www.ibm.com/docs/en/cognos-analytics/11.1.0?topic=1117-release-fp4-november-2021",
			"type": "Change Log"
		}
	]
}
